<?php

return [
    'products' => [
        'enabled' => true,

        'fields' => [
            'name',
            'internal_reference',
            'sku',
            'image_path',
            'barcode',
            'sale_price',
            'purchase_price',
            'standard_cost',
            'last_purchase_cost',
            'product_category_id',
            'inventory_unit_id',
            'product_type',
            'tracking',
            'costing_method',
            'sat_product_service_code',
            'sat_unit_code',
            'available_in_pos',
            'can_be_sold',
            'can_be_purchased',
            'is_active',
            'inventory_account_id',
            'cogs_account_id',
            'sales_income_account_id',
        ],

        'snapshot_fields' => [
            'id',
            'company_id',
            'name',
            'internal_reference',
            'sku',
            'barcode',
            'sale_price',
            'purchase_price',
            'standard_cost',
            'product_category_id',
            'inventory_unit_id',
            'product_type',
            'tracking',
            'costing_method',
            'sat_product_service_code',
            'sat_unit_code',
            'available_in_pos',
            'can_be_sold',
            'can_be_purchased',
            'is_active',
        ],
    ],
];
